default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: ####
  host: localhost

development:
  <<: *default
  database: microblogdb
  
test:
  <<: *default
  database: microblogtestdb

# Add similar configurations for other environments (e.g., test, production)
